# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('favourite_team', models.CharField(max_length=100)),
                ('wallet', models.FloatField(default=100)),
                ('game_week_points', models.IntegerField(default=100)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
    ]
