# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_injured', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=3)),
                ('real_team', models.CharField(max_length=50)),
            ],
        ),
    ]
