# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='kit_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
