# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_footballer_kit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='game_week_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballer',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='footballer',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
