# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170801_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='country',
            field=models.CharField(default='country', max_length=30),
            preserve_default=False,
        ),
    ]
